package pm;

import android.R;

/* loaded from: classes.dex */
public abstract class l {

    /* renamed from: a, reason: collision with root package name */
    public static final int[] f31223a = {R.attr.enabled, com.assetgro.stockgro.prod.R.attr.backgroundTint, com.assetgro.stockgro.prod.R.attr.backgroundTintMode, com.assetgro.stockgro.prod.R.attr.borderWidth, com.assetgro.stockgro.prod.R.attr.elevation, com.assetgro.stockgro.prod.R.attr.ensureMinTouchTargetSize, com.assetgro.stockgro.prod.R.attr.fabCustomSize, com.assetgro.stockgro.prod.R.attr.fabSize, com.assetgro.stockgro.prod.R.attr.fab_colorDisabled, com.assetgro.stockgro.prod.R.attr.fab_colorNormal, com.assetgro.stockgro.prod.R.attr.fab_colorPressed, com.assetgro.stockgro.prod.R.attr.fab_colorRipple, com.assetgro.stockgro.prod.R.attr.fab_elevationCompat, com.assetgro.stockgro.prod.R.attr.fab_hideAnimation, com.assetgro.stockgro.prod.R.attr.fab_label, com.assetgro.stockgro.prod.R.attr.fab_progress, com.assetgro.stockgro.prod.R.attr.fab_progress_backgroundColor, com.assetgro.stockgro.prod.R.attr.fab_progress_color, com.assetgro.stockgro.prod.R.attr.fab_progress_indeterminate, com.assetgro.stockgro.prod.R.attr.fab_progress_max, com.assetgro.stockgro.prod.R.attr.fab_progress_showBackground, com.assetgro.stockgro.prod.R.attr.fab_shadowColor, com.assetgro.stockgro.prod.R.attr.fab_shadowRadius, com.assetgro.stockgro.prod.R.attr.fab_shadowXOffset, com.assetgro.stockgro.prod.R.attr.fab_shadowYOffset, com.assetgro.stockgro.prod.R.attr.fab_showAnimation, com.assetgro.stockgro.prod.R.attr.fab_showShadow, com.assetgro.stockgro.prod.R.attr.fab_size, com.assetgro.stockgro.prod.R.attr.hideMotionSpec, com.assetgro.stockgro.prod.R.attr.hoveredFocusedTranslationZ, com.assetgro.stockgro.prod.R.attr.maxImageSize, com.assetgro.stockgro.prod.R.attr.pressedTranslationZ, com.assetgro.stockgro.prod.R.attr.rippleColor, com.assetgro.stockgro.prod.R.attr.shapeAppearance, com.assetgro.stockgro.prod.R.attr.shapeAppearanceOverlay, com.assetgro.stockgro.prod.R.attr.showMotionSpec, com.assetgro.stockgro.prod.R.attr.useCompatPadding};

    /* renamed from: b, reason: collision with root package name */
    public static final int[] f31224b = {com.assetgro.stockgro.prod.R.attr.menu_animationDelayPerItem, com.assetgro.stockgro.prod.R.attr.menu_backgroundColor, com.assetgro.stockgro.prod.R.attr.menu_buttonSpacing, com.assetgro.stockgro.prod.R.attr.menu_buttonToggleAnimation, com.assetgro.stockgro.prod.R.attr.menu_colorNormal, com.assetgro.stockgro.prod.R.attr.menu_colorPressed, com.assetgro.stockgro.prod.R.attr.menu_colorRipple, com.assetgro.stockgro.prod.R.attr.menu_fab_hide_animation, com.assetgro.stockgro.prod.R.attr.menu_fab_label, com.assetgro.stockgro.prod.R.attr.menu_fab_show_animation, com.assetgro.stockgro.prod.R.attr.menu_fab_size, com.assetgro.stockgro.prod.R.attr.menu_icon, com.assetgro.stockgro.prod.R.attr.menu_labels_colorNormal, com.assetgro.stockgro.prod.R.attr.menu_labels_colorPressed, com.assetgro.stockgro.prod.R.attr.menu_labels_colorRipple, com.assetgro.stockgro.prod.R.attr.menu_labels_cornerRadius, com.assetgro.stockgro.prod.R.attr.menu_labels_customFont, com.assetgro.stockgro.prod.R.attr.menu_labels_ellipsize, com.assetgro.stockgro.prod.R.attr.menu_labels_hideAnimation, com.assetgro.stockgro.prod.R.attr.menu_labels_margin, com.assetgro.stockgro.prod.R.attr.menu_labels_maxLines, com.assetgro.stockgro.prod.R.attr.menu_labels_padding, com.assetgro.stockgro.prod.R.attr.menu_labels_paddingBottom, com.assetgro.stockgro.prod.R.attr.menu_labels_paddingLeft, com.assetgro.stockgro.prod.R.attr.menu_labels_paddingRight, com.assetgro.stockgro.prod.R.attr.menu_labels_paddingTop, com.assetgro.stockgro.prod.R.attr.menu_labels_position, com.assetgro.stockgro.prod.R.attr.menu_labels_showAnimation, com.assetgro.stockgro.prod.R.attr.menu_labels_showShadow, com.assetgro.stockgro.prod.R.attr.menu_labels_singleLine, com.assetgro.stockgro.prod.R.attr.menu_labels_style, com.assetgro.stockgro.prod.R.attr.menu_labels_textColor, com.assetgro.stockgro.prod.R.attr.menu_labels_textSize, com.assetgro.stockgro.prod.R.attr.menu_openDirection, com.assetgro.stockgro.prod.R.attr.menu_shadowColor, com.assetgro.stockgro.prod.R.attr.menu_shadowRadius, com.assetgro.stockgro.prod.R.attr.menu_shadowXOffset, com.assetgro.stockgro.prod.R.attr.menu_shadowYOffset, com.assetgro.stockgro.prod.R.attr.menu_showShadow};
}
